import { state } from './state.js';

const FETCH_TIMEOUT = 15000;

// HTML is stored per language ({ en, es }); CSS and JavaScript are shared strings.
const inLanguage = (source) => (typeof source === 'string' ? source : source[state.lang]);

/**
 * Loads live-source.json (generated by `npm run build`) and keeps the HTML of the
 * current language. Cached until the portfolio is destroyed.
 */
export async function loadSource() {
  if (state.data) return state.data;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT);
  try {
    const response = await fetch('live-source.json', { signal: controller.signal });
    if (!response.ok) throw new Error('Source unavailable');
    const source = await response.json();
    state.data = {
      ...source,
      phases: source.phases.map((phase) => ({
        ...phase,
        source: inLanguage(phase.source),
        prelude: phase.prelude && inLanguage(phase.prelude),
      })),
    };
    return state.data;
  } finally {
    clearTimeout(timeout);
  }
}
